[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  format = "esm"

[build.environment]
  NODE_VERSION = "18"

# Redirecionamento da API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Fallback do React (impede erro 404 ao atualizar a página)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
